# Input configs

ramping_points: 1000
waiting_points: 2500

perturbation_time: 0.6


# target: [0,1,1,0]     
inputs: [2, 3, 6]

# Lock-in configs

perturbation_frequencies: [580, 615, 0, 0, 510, 475, 0]
perturbation_amplitudes: [0.015, 0.015, 0, 0, 0.010, 0.015, 0] # [0.0, 0.03, 0.03, 0.015, 0.015, 0.03, 0.03]
phase_threshold: 90
cutoff_frequency: 10
filter_order: 2

driver:
  instruments_setup: 
    activation_sampling_frequency: 20480 # Digital-to-Analogue Converter module update rate
    readout_sampling_frequency: 204800 # Analogue-to-Digital Converter sampling rate
    average_io_point_difference: True # Averaging mode of the ADC output;
